# Generated by Django 5.2.17 on 2026-09-02 12:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense")],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("salary", "Salary"),
                            ("freelance", "Freelance"),
                            ("business", "Business"),
                            ("investment", "Investment"),
                            ("food", "Food"),
                            ("transport", "Transport"),
                            ("shopping", "Shopping"),
                            ("rent", "Rent"),
                            ("utilities", "Utilities"),
                            ("health", "Health"),
                            ("education", "Education"),
                            ("entertainment", "Entertainment"),
                            ("subscriptions", "Subscriptions"),
                            ("bills", "Bills"),
                            ("travel", "Travel"),
                            ("family", "Family"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
    ]
