# Generated by Django 5.1.2 on 2026-09-03 06:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("loan_name", models.CharField(max_length=120)),
                (
                    "loan_type",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("car", "Car"),
                            ("bike", "Bike"),
                            ("personal", "Personal"),
                            ("education", "Education"),
                            ("credit_card", "Credit Card EMI"),
                            ("others", "Others"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "principal_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Anual Interest Rate (%)",
                        max_digits=5,
                    ),
                ),
                ("tenure_months", models.PositiveIntegerField()),
                ("emi_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "start_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("end_date", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "outstanding_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EMIPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installment_number", models.PositiveIntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "principal_component",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "interest_component",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("paid_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="finance.loan",
                    ),
                ),
            ],
        ),
    ]
