# Generated by Django 5.1.2 on 2026-09-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_loan_emipayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("completed", "Ccompleted"),
                    ("closed", "Closed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
