# Generated by Django 5.1.2 on 2026-09-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_alter_transaction_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="emipayment",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
