# Generated by Django 5.1.2 on 2026-09-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_emipayment_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="emi_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
