# Generated by Django 5.1.2 on 2026-09-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_alter_loan_emi_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
