# Generated by Django 5.1.2 on 2026-09-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_loan_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("income", "Income"),
                    ("expense", "Expense"),
                    ("investment", "Investment"),
                ],
                max_length=10,
            ),
        ),
    ]
